engines:
  eslint:
    enabled: true
    channel: 'eslint-8'
    config:
      config: '.eslintrc.yaml'
    checks:
      complexity:
        enabled: false

ratings:
  paths:
    - '**.js'

checks:
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 11
